export const tTokensList = [
	{
		name: 'ADA',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tADA.png',
		address: '',
		depositaddress: '',
	},
	{
		name: 'BNB',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tBNB.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'BTC',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tBTC.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'DASH',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tDASH.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'DCR',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tDCR.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'EOS',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tEOS.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'LTC',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tLTC.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'NANO',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tNANO.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'NEO',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tNEO.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'TRX',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tTRX.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'WAVES',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tWAVES.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'XLM',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tXLM.png',
		address: '',
			depositaddress: '',
	},
	{
		name: 'XMR',
		image: 'https://raw.githubusercontent.com/thirmprotocol/Assets/master/icons/tXMR.png',
		address: '',
			depositaddress: '',
	},
];
